version: '3'

services:
  db:
    image: postgres
    container_name: api
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: senha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql